import os
print('\n'*3)
pwd =os.getcwd()
print('GITHUB_Blog安装程序')
print('请输入你的网页仓库目录')
print('例:  /sdcard/qd/1019157263.github.io')
dict=input('>>>')
open('index.config','w').write(str({'dz':dict}))
print('写入成功')
print('正在安装jinja2模板引擎...')
os.system('pip install jinja2')
print('正在安装pylsy可视化...')
os.system('pip install pylsy')

print('当前目录:'+pwd)
fa=open('/data/data/com.termux/files/home/.bashrc','r').read()
a=open('/data/data/com.termux/files/home/.bashrc','a+')
a.write('\n')
a.write(f"alias blog='cd {pwd};python {pwd}/main.py'")
a=open('/data/data/com.termux/files/home/.bashrc','r').read()
print('写入命令位置:'+a)
os.chdir('/data/data/com.termux/files/home/')
os.system('pwd')
os.system('source  .bashrc')
print('\n'*2)
print('安装完成')
print('输入:Blog启动博客系统')